In [327]:
import numpy as np
import pandas as pd

In [328]:
heart = pd.read_csv("C:/Users/vinay/OneDrive/Desktop/DataSets for ML/heart_attack_dataset.csv")

In [329]:
heart.describe()

,Age,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,StressLevel,Income,MaxHeartRate,ST_Depression,NumberOfMajorVessels,PreviousHeartAttack,StrokeHistory
count,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000
mean,56.975151,199.455844,134.508234,89.495043,29.006733,0.499225,0.500987,0.500973,0.499901,3.003475,2.000048,5.001885,110033.409913,149.463896,2.501799,1.498525,0.496938,0.500815
std,15.867016,57.723381,25.984528,17.342658,6.345460,0.500000,0.500000,0.500000,0.500001,2.000114,1.414572,2.582025,51961.721991,28.849990,1.443696,1.118003,0.499991,0.500000
min,30.000000,100.000000,90.000000,60.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,20000.000000,100.000000,0.000000,0.000000,0.000000,0.000000
25%,43.000000,149.000000,112.000000,74.000000,23.500000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.000000,64957.250000,124.000000,1.250000,0.000000,0.000000,0.000000
50%,57.000000,199.000000,134.000000,89.000000,29.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,5.000000,110111.000000,149.000000,2.500000,1.000000,0.000000,1.000000
75%,71.000000,249.000000,157.000000,105.000000,34.500000,1.000000,1.000000,1.000000,1.000000,5.000000,3.000000,7.000000,155012.000000,174.000000,3.750000,2.000000,1.000000,1.000000
max,84.000000,299.000000,179.000000,119.000000,40.000000,1.000000,1.000000,1.000000,1.000000,6.000000,4.000000,9.000000,199999.000000,199.000000,5.000000,3.000000,1.000000,1.000000

In [330]:
heart.isnull().sum()

Age                      0
Gender                   0
Cholesterol              0
BloodPressure            0
HeartRate                0
BMI                      0
Smoker                   0
Diabetes                 0
Hypertension             0
FamilyHistory            0
PhysicalActivity         0
AlcoholConsumption       0
Diet                     0
StressLevel              0
Ethnicity                0
Income                   0
EducationLevel           0
Medication               0
ChestPainType            0
ECGResults               0
MaxHeartRate             0
ST_Depression            0
ExerciseInducedAngina    0
Slope                    0
NumberOfMajorVessels     0
Thalassemia              0
PreviousHeartAttack      0
StrokeHistory            0
Residence                0
EmploymentStatus         0
MaritalStatus            0
Outcome                  0
dtype: int64

In [331]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder

In [332]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372974 entries, 0 to 372973
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Age                    372974 non-null  int64
 1   Gender                 372974 non-null  object
 2   Cholesterol            372974 non-null  int64
 3   BloodPressure          372974 non-null  int64
 4   HeartRate              372974 non-null  int64
 5   BMI                    372974 non-null  float64
 6   Smoker                 372974 non-null  int64
 7   Diabetes               372974 non-null  int64
 8   Hypertension           372974 non-null  int64
 9   FamilyHistory          372974 non-null  int64
 10  PhysicalActivity       372974 non-null  int64
 11  AlcoholConsumption     372974 non-null  int64
 12  Diet                   372974 non-null  object
 13  StressLevel            372974 non-null  int64
 14  Ethnicity              372974 non-null  object
 15  Income                 372974 non-null  int64
 16  EducationLevel         372974 non-null  object
 17  Medication             372974 non-null  object
 18  ChestPainType          372974 non-null  object
 19  ECGResults             372974 non-null  object
 20  MaxHeartRate           372974 non-null  int64
 21  ST_Depression          372974 non-null  float64
 22  ExerciseInducedAngina  372974 non-null  object
 23  Slope                  372974 non-null  object
 24  NumberOfMajorVessels   372974 non-null  int64
 25  Thalassemia            372974 non-null  object
 26  PreviousHeartAttack    372974 non-null  int64
 27  StrokeHistory          372974 non-null  int64
 28  Residence              372974 non-null  object
 29  EmploymentStatus       372974 non-null  object
 30  MaritalStatus          372974 non-null  object
 31  Outcome                372974 non-null  object
dtypes: float64(2), int64(16), object(14)
memory usage: 91.1+ MB

In [333]:
X = heart.drop(columns='Outcome')
Y = heart['Outcome']

In [334]:
X

,Age,Gender,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,...,ST_Depression,ExerciseInducedAngina,Slope,NumberOfMajorVessels,Thalassemia,PreviousHeartAttack,StrokeHistory,Residence,EmploymentStatus,MaritalStatus
0,31,Male,194,162,71,22.9,0,1,0,0,...,0.52,Yes,Downsloping,1,Normal,0,0,Suburban,Retired,Single
1,69,Male,208,148,93,33.9,1,1,0,0,...,3.79,Yes,Upsloping,2,Normal,0,0,Suburban,Unemployed,Married
2,34,Female,132,161,94,34.0,0,0,1,1,...,0.17,Yes,Upsloping,0,Normal,1,0,Rural,Retired,Single
3,53,Male,268,134,91,35.0,0,1,1,0,...,0.67,Yes,Flat,0,Reversible defect,1,0,Suburban,Retired,Widowed
4,57,Female,203,140,75,30.1,0,1,0,0,...,5.00,Yes,Flat,0,Fixed defect,1,0,Rural,Retired,Married
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372969,49,Female,285,131,79,27.6,0,1,1,1,...,0.17,Yes,Flat,2,Fixed defect,1,0,Urban,Employed,Married
372970,77,Male,197,159,64,33.5,0,1,0,1,...,1.73,No,Downsloping,3,Fixed defect,0,1,Urban,Employed,Married
372971,53,Female,243,94,84,34.7,1,1,1,0,...,3.15,Yes,Flat,3,Reversible defect,1,1,Urban,Retired,Married
372972,78,Female,291,93,78,29.3,1,1,0,1,...,4.21,Yes,Upsloping,1,Fixed defect,0,0,Urban,Employed,Married
372973,71,Male,127,153,83,39.7,1,1,1,0,...,0.43,No,Upsloping,3,Fixed defect,1,1,Urban,Unemployed,Single

In [335]:
Y

0         No Heart Attack
1         No Heart Attack
2            Heart Attack
3         No Heart Attack
4            Heart Attack
               ...
372969    No Heart Attack
372970       Heart Attack
372971       Heart Attack
372972    No Heart Attack
372973       Heart Attack
Name: Outcome, Length: 372974, dtype: object

In [336]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

In [337]:
categorical_cols

['Gender',
 'Diet',
 'Ethnicity',
 'EducationLevel',
 'Medication',
 'ChestPainType',
 'ECGResults',
 'ExerciseInducedAngina',
 'Slope',
 'Thalassemia',
 'Residence',
 'EmploymentStatus',
 'MaritalStatus']

In [338]:
encoder = OneHotEncoder(sparse_output=False, drop='first')

In [339]:
encoded_data = encoder.fit_transform(X[categorical_cols])

In [340]:
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

In [341]:
X_encoded = pd.concat([X.drop(columns=categorical_cols), encoded_df], axis=1)

In [342]:
print(X_encoded)

        Age  Cholesterol  BloodPressure  HeartRate   BMI  Smoker  Diabetes  \
0        31          194            162         71  22.9       0         1
1        69          208            148         93  33.9       1         1
2        34          132            161         94  34.0       0         0
3        53          268            134         91  35.0       0         1
4        57          203            140         75  30.1       0         1
...     ...          ...            ...        ...   ...     ...       ...
372969   49          285            131         79  27.6       0         1
372970   77          197            159         64  33.5       0         1
372971   53          243             94         84  34.7       1         1
372972   78          291             93         78  29.3       1         1
372973   71          127            153         83  39.7       1         1

        Hypertension  FamilyHistory  PhysicalActivity  ...  Slope_Upsloping  \
0                  0              0                 6  ...              0.0
1                  0              0                 1  ...              1.0
2                  1              1                 1  ...              1.0
3                  1              0                 6  ...              0.0
4                  0              0                 4  ...              0.0
...              ...            ...               ...  ...              ...
372969             1              1                 2  ...              0.0
372970             0              1                 6  ...              0.0
372971             1              0                 2  ...              0.0
372972             0              1                 3  ...              1.0
372973             1              0                 3  ...              1.0

        Thalassemia_Normal  Thalassemia_Reversible defect  Residence_Suburban  \
0                      1.0                            0.0                 1.0
1                      1.0                            0.0                 1.0
2                      1.0                            0.0                 0.0
3                      0.0                            1.0                 1.0
4                      0.0                            0.0                 0.0
...                    ...                            ...                 ...
372969                 0.0                            0.0                 0.0
372970                 0.0                            0.0                 0.0
372971                 0.0                            1.0                 0.0
372972                 0.0                            0.0                 0.0
372973                 0.0                            0.0                 0.0

        Residence_Urban  EmploymentStatus_Retired  \
0                   0.0                       1.0
1                   0.0                       0.0
2                   0.0                       1.0
3                   0.0                       1.0
4                   0.0                       1.0
...                 ...                       ...
372969              1.0                       0.0
372970              1.0                       0.0
372971              1.0                       1.0
372972              1.0                       0.0
372973              1.0                       0.0

        EmploymentStatus_Unemployed  MaritalStatus_Married  \
0                               0.0                    0.0
1                               1.0                    1.0
2                               0.0                    0.0
3                               0.0                    0.0
4                               0.0                    1.0
...                             ...                    ...
372969                          0.0                    1.0
372970                          0.0                    1.0
372971                          0.0                    1.0
372972                          0.0                    1.0
372973                          1.0                    0.0

        MaritalStatus_Single  MaritalStatus_Widowed
0                        1.0                    0.0
1                        0.0                    0.0
2                        1.0                    0.0
3                        0.0                    1.0
4                        0.0                    0.0
...                      ...                    ...
372969                   0.0                    0.0
372970                   0.0                    0.0
372971                   0.0                    0.0
372972                   0.0                    0.0
372973                   1.0                    0.0

[372974 rows x 45 columns]

In [343]:
X_encoded

,Age,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,...,Slope_Upsloping,Thalassemia_Normal,Thalassemia_Reversible defect,Residence_Suburban,Residence_Urban,EmploymentStatus_Retired,EmploymentStatus_Unemployed,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed
0,31,194,162,71,22.9,0,1,0,0,6,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,69,208,148,93,33.9,1,1,0,0,1,...,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,34,132,161,94,34.0,0,0,1,1,1,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,53,268,134,91,35.0,0,1,1,0,6,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
4,57,203,140,75,30.1,0,1,0,0,4,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372969,49,285,131,79,27.6,0,1,1,1,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
372970,77,197,159,64,33.5,0,1,0,1,6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
372971,53,243,94,84,34.7,1,1,1,0,2,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
372972,78,291,93,78,29.3,1,1,0,1,3,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
372973,71,127,153,83,39.7,1,1,1,0,3,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [344]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_normalized = pd.DataFrame(scaler.fit_transform(X_encoded), columns=X_encoded.columns)

In [345]:
le = LabelEncoder()
Y_encoded = le.fit_transform(Y)

In [346]:
X_train, X_test, Y_train, Y_test = train_test_split(X_normalized, Y_encoded, test_size=0.2, random_state=42, stratify=Y_encoded)

In [347]:
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, Y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [348]:
Y_pred = model.predict(X_test)

In [349]:
from sklearn.metrics import accuracy_score, classification_report

In [350]:
label_mapping = {0: "No Heart Attack", 1: "Heart Attack"}
Y_pred_labels = np.vectorize(label_mapping.get)(Y_pred)

In [351]:
accuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:\n", classification_report(Y_test, Y_pred))

Accuracy: 0.4989
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.49      0.49     37263
           1       0.50      0.51      0.50     37332

    accuracy                           0.50     74595
   macro avg       0.50      0.50      0.50     74595
weighted avg       0.50      0.50      0.50     74595

In [352]:
def predict_heart_attack(user_input):
    user_df = pd.DataFrame([user_input], columns=X_normalized.columns)

    user_df_scaled = scaler.transform(user_df)

    prediction = model.predict(user_df_scaled)[0]

    return "Heart Attack" if prediction == 1 else "No Heart Attack"

user_input_example = X_normalized.iloc[0].to_dict()

result = predict_heart_attack(user_input_example)
print("Prediction:", result)

Prediction: No Heart Attack

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(